
class Error:
    INSUFFICIENT_AMOUNT = "INSUFFICIENT AMOUNT"
    POOL_STATE = "POOL STATE CHANGED"
    ADMIN_ERROR = "NOT ADMIN"
    AMOUNT_ERROR = "INVALID AMOUNT"
    TOKEN_ERROR = "TOKEN ERROR"
    NOT_ADMIN = "NOT ADMIN"
    INITIALIZED_ERROR = "ALREADY INITIALIZED"
    NO_TEZ = "No tez allowed here"